export enum ActionTypes {
  ADDED = 'ADDED',
  ADDRESS_CHANGED = 'ADDRESS CHANGED',
  CORRECTED = 'CORRECTED',
  EDITED = 'EDITED',
  EMAIL_CHANGED = 'EMAIL CHANGED',
  NAME_CHANGED = 'NAME CHANGED',
  REMOVED = 'REMOVED'
}
