/** List of actions authorized via roles. See Authorizations module. */
export enum AuthorizedActions {
  ALTERATION_FILING,
  BLANK_CERTIFY_STATE,
  BLANK_COMPLETING_PARTY,
  CORRECTION_FILING,
  COURT_ORDER_POA,
  EDITABLE_CERTIFY_NAME,
  EDITABLE_COMPLETING_PARTY,
  FILE_AND_PAY,
  FIRM_CHANGE_FILING,
  FIRM_CONVERSION_FILING,
  FIRM_EDITABLE_DBA,
  FIRM_NO_HELP_SECTION,
  FIRM_NO_MIN_START_DATE,
  FIRM_REPLACE_PERSON,
  NO_CONTACT_INFO,
  RESTORATION_FILING,
  SAVE_DRAFT,
  SPECIAL_RESOLUTION_FILING,
  STAFF_BREADCRUMBS,
  STAFF_PAYMENT,
  THIRD_PARTY_CERTIFY_STMT
}
