/**
 * List of actions authorized via roles. See Authorizations module.
 * Ultimately, this will be combined into the Authorization Roles enum.
 */
export enum AuthorizedActions {
  ALTERATION_FILING,
  // BLANK_CERTIFY_STATE,
  BLANK_COMPLETING_PARTY,
  COOP_CORRECTION_FILING,
  CORP_CORRECTION_FILING,
  // COURT_ORDER_POA,
  // EDITABLE_CERTIFY_NAME,
  EDITABLE_COMPLETING_PARTY,
  FILE_AND_PAY,
  // FIRM_ADD_BUSINESS,
  FIRM_CHANGE_FILING,
  FIRM_CONVERSION_FILING,
  FIRM_CORRECTION_FILING,
  // FIRM_EDITABLE_COMPLETING_PARTY,
  // FIRM_EDITABLE_EMAIL_ADDRESS,
  FIRM_NO_HELP_SECTION,
  FIRM_NO_MIN_START_DATE,
  FIRM_REPLACE_PERSON,
  // NO_COMPLETING_PARTY_MESSAGE_BOX,
  // NO_CONTACT_INFO,
  RESTORATION_FILING,
  SAVE_DRAFT,
  // SBC_BREADCRUMBS,
  SPECIAL_RESOLUTION_FILING,
  STAFF_BREADCRUMBS,
  // STAFF_COMMENTS,
  STAFF_PAYMENT,
  THIRD_PARTY_CERTIFY_STMT
}
