export enum FilingCodes {
  ALTERATION = 'ALTER',
  CORRECTION = 'CRCTN',
  FM_CHANGE = 'FMCHANGE',
  FM_CONVERSION = 'FMCONV',
  FM_CORRECTION = 'FMCORR',
  INCORPORATION_BC = 'BCINC',
  INCORPORATION_CP = 'OTINC',
  SPECIAL_RESOLUTION = 'SPRLN'
}
