export enum RoleTypes {
  APPLICANT = 'Applicant',
  COMPLETING_PARTY = 'Completing Party',
  CUSTODIAN = 'Custodian',
  DIRECTOR = 'Director',
  INCORPORATOR = 'Incorporator',
  LIQUIDATOR = 'Liquidator',
  PARTNER = 'Partner',
  PROPRIETOR = 'Proprietor',
  OFFICER = 'Officer',
  CEO = 'Chief Executive Officer',
  CFO = 'Chief Financial Officer',
  PRESIDENT = 'President',
  VICE_PRESIDENT = 'Vice President',
  CHAIR = 'Chair',
  TREASURER = 'Treasurer',
  SECRETARY = 'Secretary',
  ASSISTANT_SECRETARY = 'Assistant Secretary',
  OTHER = 'Other',
  SUBSCRIBER = 'Subscriber'
}
