import { AlterationFlagsReviewCertifyIF, ChangeFlagsReviewCertifyIF, ConversionFlagsReviewCertifyIF,
  SpecialResolutionFlagsReviewCertifyIF, FlagsCompanyInfoIF, BenStaffCorrectionFlagsReviewCertifyIF,
  BenClientCorrectionFlagsReviewCertifyIF, FirmClientCorrectionFlagsReviewCertifyIF,
  FirmStaffCorrectionFlagsReviewCertifyIF } from './'

export interface ValidationFlagsIF {
  appValidate: boolean
  componentValidate: boolean
  alterationFlagsReviewCertify: AlterationFlagsReviewCertifyIF,
  changeFlagsReviewCertify: ChangeFlagsReviewCertifyIF,
  conversionFlagsReviewCertify: ConversionFlagsReviewCertifyIF,
  specialResolutionFlagsReviewCertify: SpecialResolutionFlagsReviewCertifyIF,
  benStaffCorrectionFlagsReviewCertify: BenStaffCorrectionFlagsReviewCertifyIF,
  benClientCorrectionFlagsReviewCertify: BenClientCorrectionFlagsReviewCertifyIF,
  firmClientCorrectionFlagsReviewCertify: FirmClientCorrectionFlagsReviewCertifyIF,
  firmStaffCorrectionFlagsReviewCertify: FirmStaffCorrectionFlagsReviewCertifyIF,
  flagsCompanyInfo: FlagsCompanyInfoIF
}
