export { default as Actions } from './Actions.vue'
export { BreadCrumb } from '@bcrs-shared-components/bread-crumb'
export { default as BcRegContacts } from './BcRegContacts.vue'
export { default as CertifySection } from './CertifySection.vue'
export { default as CompletingParty } from './CompletingParty.vue'
export { default as Detail } from './Detail.vue'
export { default as EffectiveDateTime } from './EffectiveDateTime.vue'
export { default as EntityInfo } from './EntityInfo.vue'
export { default as ErrorContact } from './ErrorContact.vue'
export { default as StaffPayment } from './StaffPayment.vue'
export * from './dialogs'
export * from './YourCompany'
export * from './PeopleAndRoles'
export * from './ShareStructure'

// Shared Components
export { CourtOrderPoa } from '@bcrs-shared-components/court-order-poa'
export { ContactInfo } from '@bcrs-shared-components/contact-info'
// export { NatureOfBusiness } from '@bcrs-shared-components/nature-of-business'
