export { default as AccountAuthorizationDialog } from './AccountAuthorizationDialog.vue'
export { default as ConfirmRemoveDialog } from './ConfirmRemoveDialog.vue'
export { ConfirmDialog } from '@bcrs-shared-components/confirm-dialog'
export { default as DeleteErrorDialog } from './DeleteErrorDialog.vue'
export { default as FetchErrorDialog } from './FetchErrorDialog.vue'
export { default as FileAndPayInvalidNameRequestDialog } from './FileAndPayInvalidNameRequestDialog.vue'
export { default as NameRequestErrorDialog } from './NameRequestErrorDialog.vue'
export { default as PaymentErrorDialog } from './PaymentErrorDialog.vue'
export { default as ResolutionDateDialog } from './ResolutionDateDialog.vue'
export { default as SaveErrorDialog } from './SaveErrorDialog.vue'
