name: Business Edit UI CI

on:
  pull_request:
    branches:
      - main
      - feature*
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  business-edit-ui-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/frontend-ci.yaml@main
    with:
      node_version: "20.5.1"
      app_name: "business-edit-ui"
